package org.hisp.dhis.common.screens

enum class Components(val label: String) {
    ICON_BUTTON("Icon Button"),
    BUTTON("Button"),
    FORM_SHELLS("Form Shells"),
    INPUT_TEXT("Input Text"),
    INPUT_LONG_TEXT("Input Long Text"),
    INPUT_POSITIVE_INTEGER_OR_ZERO("Input Positive Integer Or Zero"),
    INPUT_NEGATIVE_INTEGER("Input Negative Integer"),
    INPUT_PERCENTAGE("Input Percentage"),
    INPUT_POSITIVE_INTEGER("Input Positive Integer"),
    INPUT_INTEGER("Input Integer"),
    INPUT_NUMBER("Input Number"),
    INPUT_LETTER("Input Letter"),
    BOTTOM_SHEET_HEADER("Bottom Sheet Header"),
    TAGS("Tags"),
    SECTIONS("Sections"),
    RADIO("Radio"),
    CHECK_BOX("Check Box"),
    FORMS_COMPONENTS("Form components"),
    PROGRESS("Progress"),
    SUPPORTING_TEXT("Supporting Text"),
    LEGEND("Legend"),
    LEGEND_DESCRIPTION("Legend description"),
    INPUT("Input"),
    BUTTON_BLOCK("Button block"),
    CHIPS("Chips"),
    BADGES("Badges"),
    METADATA_AVATAR("Metadata Avatar"),
    INPUT_RADIO_BUTTON("Input Radio Button"),
    SWITCH("Switch"),
    INPUT_MATRIX("Input Matrix"),
    INPUT_SEQUENTIAL("Input Sequential"),
}
