package org.hisp.dhis.common.screens

enum class Components(val label: String) {
    ICON_BUTTON("Icon Button"),
    BUTTON("Button"),
    RADIO("Radio"),
    CHECK_BOX("Check Box"),
    FORMS_COMPONENTS("Form components"),
    PROGRESS("Progress"),
    SUPPORTING_TEXT("Supporting Text"),
    LEGEND("Legend"),
    INPUT("Input"),
    LEGEND_DESCRIPTION("Legend description"),
    BUTTON_BLOCK("Button block"),
    INPUT_TEXT("Input Text"),
    INPUT_NEGATIVE_INTEGER("Input Negative Integer"),
    INPUT_PERCENTAGE("Input Percentage"),
    INPUT_POSITIVE_INTEGER("Input Positive Integer"),
    INPUT_INTEGER("Input Integer"),
    INPUT_NUMBER("Input Number"),
    FORM_SHELLS("Form Shells"),
    BOTTOM_SHEET("Bottom Sheet"),
    TAGS("Tags"),
    SECTIONS("Sections"),
    INPUT_LONG_TEXT("Input Long Text"),
}
