package org.hisp.dhis.common.screens

enum class Groups(val label: String) {
    ACTION_INPUTS("Action inputs"),
    BASIC_TEXT_INPUTS("Basic text Inputs"),
    BOTTOM_SHEETS("Bottom sheet components"),
    BUTTONS("Buttons"),
    CARDS("List Cards and Card details"),
    CHIPS("Chips"),
    LEGEND("Legend"),
    PROGRESS_INDICATOR("Progress Indicator"),
    SECTIONS("Sections"),
    SEARCH_BAR("Search Bar"),
    TOGGLEABLE_INPUTS("Options"),
    TAGS("Tags"),
    BADGES("Badges"),
    METADATA_AVATAR("Metadata Avatar"),
    INDICATOR("Indicators"),
    PARAMETER_SELECTOR("Parameter selector"),
    NAVIGATION_BAR("Navigation Bar"),
    TOP_BAR("Top Bar"),
    MENU("Menu"),
    NO_GROUP_SELECTED("No group selected"),
    LOCATION_SEARCH_BAR("Location Search Bar"),
    TABLE("Table"),
    TABS("Tabs"),
}
