package org.hisp.dhis.mobile.ui.designsystem.component.navigationBar

object NavigationBarTestTags {
    const val NAVIGATION_BAR_CONTAINER = "NAVIGATION_BAR_CONTAINER"
    const val NAVIGATION_BAR_BORDER = "NAVIGATION_BAR_BORDER"
    const val NAVIGATION_BAR = "NAVIGATION_BAR"
    const val NAVIGATION_BAR_ITEM_PREFIX = "NAVIGATION_BAR_ITEM_"
    const val NAVIGATION_BAR_ITEM_LABEL_PREFIX = "NAVIGATION_BAR_ITEM_LABEL_"
    const val NAVIGATION_BAR_ITEM_BADGE_PREFIX = "NAVIGATION_BAR_ITEM_BADGE_"
}
