name: Continuous deployment

env:
  main_project_module: android

on:
  push:
    branches:
      - develop # Automatically generates snapshot versions

  workflow_dispatch: ## manually generates release versions
    inputs:
      release_version:
        description: 'please, enter the release version'
        required: true
        type: string

jobs:
  create_release:
    runs-on: windows-latest
    if: ${{ (inputs.release_version) && (inputs.release_version != '') }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]  # Add Windows, Linux, macOS

    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Debugging: Check the current directory and list files
      - name: Print working directory
        run: pwd

      - name: List files in main project module
        run: ls -R ${{ env.main_project_module }}

      - name: List files in desktop build directory
        run: ls -R desktop/build

      # Build APK only on Windows
      - name: Build APK (Android Module)
        if: ${{ matrix.os == 'windows-latest' }}
        run: ./gradlew assembleDebug

      # Create desktop JAR for each OS
      - name: Create desktop jar for ${{ matrix.os }}
        run: ./gradlew packageUberJarForCurrentOS

      # Upload APK for Windows
      - name: Upload APK (only on Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/*.apk

      # Upload desktop JAR for each OS
      - name: Upload Desktop JAR
        uses: actions/upload-artifact@v3
        with:
          name: desktop-jar-${{ matrix.os }}
          path: desktop/build/compose/jars/*.jar

  # Separate job to download artifacts and create GitHub release
  github_release:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Download APK
        uses: actions/download-artifact@v3
        with:
          name: android-apk

      - name: Download Windows JAR
        uses: actions/download-artifact@v3
        with:
          name: desktop-jar-windows-latest

      - name: Download Linux JAR
        uses: actions/download-artifact@v3
        with:
          name: desktop-jar-ubuntu-latest

      - name: Download macOS JAR
        uses: actions/download-artifact@v3
        with:
          name: desktop-jar-macos-latest

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          generateReleaseNotes: true
          name: "Mobile Design system for DHIS 2 (v${{ inputs.release_version }})"
          tag: ${{ inputs.release_version }}
          artifacts: |
            android-apk.zip
#            desktop-jar-windows-latest/*.jar,
#            desktop-jar-ubuntu-latest/*.jar,
#            desktop-jar-macos-latest/*.jar
