name: Continuous deployment

env:
  main_project_module: android

on:
  push:
    branches:
      - develop # Automatically generates snapshot versions

  workflow_dispatch: ## manually generates release versions
    inputs:
      release_version:
        description: 'please, enter the release version'
        required: true
        type: string

jobs:
  #  publish:
  #    # The type of runner that the job will run on
  #    runs-on: ubuntu-latest
  #
  #    # Steps represent a sequence of tasks that will be executed as part of the job
  #    steps:
  #      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #      - uses: actions/checkout@v3
  #
  #      - name: Set Up JDK
  #        uses: actions/setup-java@v3
  #        with:
  #          distribution: 'zulu' # See 'Supported distributions' for available options
  #          java-version: '17'
  #          cache: 'gradle'
  #
  #      - name: Change wrapper permissions
  #        run: chmod +x ./gradlew
  #
  #      # Create publish to maven
  #      - name: Publish to maven
  #        run: ./.github/workflows/scripts/publish-maven.sh
  #        env:
  #          OSSRH_USERNAME: ${{ secrets.SONATYPE_OSSRH_USERNAME }}
  #          OSSRH_PASSWORD: ${{ secrets.SONATYPE_OSSRH_PASSWORD }}
  #          SIGNING_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
  #          SIGNING_PASSWORD: ${{ secrets.PGP_PASSPHRASE }}

  create_artifacts:
    runs-on: ubuntu-latest
    if: ${{ (inputs.release_version) && (inputs.release_version != '') }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Create Android APK
      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: ./gradlew assembleDebug

      # Create desktop JAR for each OS
      - name: Create desktop jar for ${{ matrix.os }}
        run: ./gradlew packageUberJarForCurrentOS

      - name: Github Release
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          generateReleaseNotes: true
          name: "Release notes - DHIS2 Design system: ${{ inputs.release_version }}"
          tag: ${{ inputs.release_version }}
          artifacts: |
            ${{ env.main_project_module }}/build/outputs/apk/debug/android-debug.apk,
            ${{ github.workspace }}/desktop/build/compose/jars/mobile-ui-windows-x64-1.0.0.jar,
            ${{ github.workspace }}/desktop/build/compose/jars/mobile-ui-linux-x64-1.0.0.jar,
            ${{ github.workspace }}/desktop/build/compose/jars/mobile-ui-macos-x64-1.0.0.jar
